name: Set Telegram webhook

on:
  workflow_dispatch:
    inputs:
      webhook_url:
        description: 'The public HTTPS URL for your webhook (eg. https://abc123.ngrok.io)'
        required: true
        type: string

jobs:
  set-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secrets
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_SECRET_TOKEN: ${{ secrets.TELEGRAM_SECRET_TOKEN }}
        run: |
          if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] || [ -z "${{ secrets.TELEGRAM_SECRET_TOKEN }}" ]; then
            echo "ERROR: TELEGRAM_BOT_TOKEN and TELEGRAM_SECRET_TOKEN must be set as repository secrets."; exit 1;
          fi
          if [ -z "${{ github.event.inputs.webhook_url }}" ]; then
            echo "ERROR: webhook_url input is required."; exit 1;
          fi

      - name: Install jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Set Telegram webhook
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_SECRET_TOKEN: ${{ secrets.TELEGRAM_SECRET_TOKEN }}
        run: |
          WEBHOOK_URL="${{ github.event.inputs.webhook_url }}/telegram-webhook/${{ secrets.TELEGRAM_SECRET_TOKEN }}"
          echo "Setting Telegram webhook to: $WEBHOOK_URL"
          RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/setWebhook?url=${WEBHOOK_URL}")
          echo "Response: $RESPONSE"

          OK=$(echo "$RESPONSE" | jq -r '.ok' 2>/dev/null || echo "false")
          if [ "$OK" != "true" ]; then
            echo "Failed to set webhook. Full response:"; echo "$RESPONSE"; exit 1
          fi
          echo "Webhook set successfully."